<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TriPC" failures="1" tests="6" name="com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest" time="287.619" errors="0" timestamp="2023-05-26T15:56:29 ICT" skipped="0">
  <testcase classname="com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest" name="runScenario" time="39.737"/>
  <system-out/>
  <testcase classname="com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest" name="runScenario" time="37.195"/>
  <system-out/>
  <testcase classname="com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest" name="runScenario" time="60.174">
    <failure message="expected [Werex sorry you declined our process!] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Werex sorry you declined our process!] but found [null]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.mgp.mdemo1.frontend.tests.stepdefinitions.WeAreSorrySteps.userShouldSeeTheMessage(WeAreSorrySteps.java:32)
at âœ½.User should see the message "Werex sorry you declined our process!"(classpath:features/SubmitAnInvalidApplication.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest" name="runScenario" time="37.498"/>
  <system-out/>
  <testcase classname="com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest" name="runScenario" time="43.464"/>
  <system-out/>
  <testcase classname="com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest" name="runScenario" time="69.551"/>
  <system-out/>
</testsuite> <!-- com.mgp.mdemo1.frontend.tests.testng.runner.RunCucumberTest -->
